####################################
#	Projekt 2 - Roller Coaster
#	
#	Autor: Martin Bazik
#	Datum 29.4.2016	
#	
#	Makefile
#####################################
CC=gcc
CFLAGS= -std=gnu99 -lpthread -Wall -Wextra -Werror -pedantic -lrt

all: proj2

tail: proj2.c
	$(CC) $(CFLAGS) -o proj2 proj2.c